export const GET_ACCOUNT = 'GET_ACCOUNT';
export const GET_ACCOUNT_DONE = 'GET_ACCOUNT_DONE';
export const GET_TOKENS = 'GET_TOKENS';
export const GET_TOKENS_DONE = 'GET_TOKENS_DONE';
export const GET_CONTRACT = 'GET_CONTRACT';
export const GET_CONTRACT_DONE = 'GET_CONTRACT_DONE';
